#!/usr/bin/env bash
# gen-large-fixture.sh — produce fixtures/specialized/large.md, a stress/perf
# fixture for termdown. Output is deterministic (no $RANDOM, no timestamps)
# so a clean re-run produces an identical file and `git diff` is meaningful.
#
# Usage:
#   ./scripts/gen-large-fixture.sh > fixtures/specialized/large.md
#
# Shape: 1 H1 + 500 H2 sections, every 50th sections is followed by an extra
# H3 to add depth, every section contains a paragraph (中英 mixed) + a nested
# list + a 3x3 table + a fenced rust code block. A ~200-row final table
# stresses the table renderer.

set -euo pipefail

SECTIONS="${SECTIONS:-500}"
H3_EVERY="${H3_EVERY:-50}"
TAIL_TABLE_ROWS="${TAIL_TABLE_ROWS:-200}"

cat <<'HEADER'
# Large Fixture — Stress / Performance Baseline

This file is **generated** by `scripts/gen-large-fixture.sh`. Do not hand-edit;
re-run the script and commit the diff. It exists to give us a manual baseline
for "does termdown stay snappy on a 200 KB / 10k-line document?" — it is **not**
wired into the snapshot tests.

HEADER

for i in $(seq 1 "$SECTIONS"); do
    cat <<SECTION
## Section $i — sample heading $i

This is paragraph one of section $i. It mixes English and 中文 so width
calculation and bidi handling get exercised on every section. Lorem ipsum dolor
sit amet, consectetur adipiscing elit. 这一段额外加一些汉字以保证每节正文都不止
一行，让大文件里的换行/滚动路径也被覆盖。

This is paragraph two of section $i with **bold**, *italic*, \`inline code\`,
and a [link](https://example.com/section-$i).

- 列表项 A of section $i
- 列表项 B of section $i
  - nested B.1
  - nested B.2 with a longer line so it wraps inside narrow terminals and we
    can spot indent bugs on the large fixture too
- 列表项 C of section $i

| Col 1 | Col 2 | Col 3 |
| ----- | ----- | ----- |
| ${i}a   | ${i}b   | ${i}c   |
| 中文 ${i} | English ${i} | 🚀 ${i} |

\`\`\`rust
fn section_${i}() -> usize {
    let n = ${i};
    n * 2
}
\`\`\`

SECTION

    if [ $((i % H3_EVERY)) -eq 0 ]; then
        cat <<DEEPER
### Section $i.1 — extra depth marker

Every ${H3_EVERY}th section gets an H3 sub-section to vary the heading depth
across the document.

DEEPER
    fi
done

# Tail table to stress the table renderer.
cat <<'TAIL_HEADER'
## Tail — Large Table Stress

The following table has many rows to exercise table rendering on long inputs.

| Index | Label     | Value | Description (mixed scripts)             |
| ----- | --------- | ----- | --------------------------------------- |
TAIL_HEADER

for i in $(seq 1 "$TAIL_TABLE_ROWS"); do
    printf '| %5d | row-%-5d | %5d | 描述行 %d / description row %d            |\n' \
        "$i" "$i" "$((i * 7))" "$i" "$i"
done

cat <<'FOOTER'

## End

Generated by `scripts/gen-large-fixture.sh`. Re-run after changing the script.
FOOTER
